### ISSUE TITLE
"Server Error" when trying to create queries

### ISSUE THREAD

**Issue by tavlima** [danmunn/redmine_mylyn_connector#19]
It seems that the "is_public" column doesn't exist anymore...

/mylyn/version?key=ae33f3a...

``` xml
<version xmlns="http://redmin-mylyncon.sf.net/api" api="2.8.2.stable" authenticated="true" authenticatedAs="thiago">
    <plugin major="2" minor="8" tiny="2">2.8.2.stable</plugin>
    <redmine>2.3.2.devel</redmine>
    <rails>3.2.13</rails>
</version>
```

Production log:

```
Started GET "/mylyn/queries?key=ae33f3ab9afdc6c6193ac24f52f6217f9ba8b33e" for 177.133.117.215 at 2013-08-14 23:26:24 +0000

ActiveRecord::StatementInvalid (PG::Error: ERROR: column queries.is_public does not exist
LINE 1: ...t join projects on project_id=projects.id WHERE ((queries.is...
                                                             ^
SELECT "queries".* FROM "queries" left join projects on project_id=projects.id WHERE ((queries.is_public = 't' OR queries.user_id = 3) AND (project_id IS NULL OR ((projects.status <> 9) AND (projects.is_public = 't' OR projects.id IN (5,4,7,1,6) OR projects.id IN (7) OR projects.id IN (7,1,3))))) ORDER BY queries.name ASC):
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1161:in `exec'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1161:in `exec_no_cache'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/active_record.rb:46:in `block in log_with_newrelic_instrumentation'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/method_tracer.rb:268:in `trace_execution_scoped'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/active_record.rb:43:in `log_with_newrelic_instrumentation'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1256:in `select'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `block in select_all'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/query_cache.rb:61:in `select_all'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/querying.rb:38:in `block in find_by_sql'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/explain.rb:41:in `logging_query_plan'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/querying.rb:37:in `find_by_sql'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/method_tracer.rb:518:in `block in find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/method_tracer.rb:268:in `trace_execution_scoped'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/method_tracer.rb:513:in `find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation.rb:171:in `exec_queries'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation.rb:160:in `block in to_a'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/explain.rb:41:in `logging_query_plan'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation.rb:159:in `to_a'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/finder_methods.rb:159:in `all'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/finder_methods.rb:105:in `find'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/finder_methods.rb:101:in `find'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/querying.rb:5:in `find'
    plugins/redmine_mylyn_connector/app/controllers/mylyn_connector/queries_controller.rb:12:in `all'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:458:in `_run__1513058003356819852__process_action__2417589544008323753__callbacks'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `block in instrument'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/notifications.rb:123:in `instrument'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:38:in `block in process_action'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:318:in `perform_action_with_newrelic_trace'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:37:in `process_action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal.rb:203:in `dispatch'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_controller/metal.rb:246:in `block in action'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:36:in `call'
    vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:68:in `block in call'
    vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
    vendor/bundle/ruby/2.0.0/gems/journey-1.0.4/lib/journey/router.rb:56:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/routing/route_set.rb:612:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-openid-1.3.1/lib/rack/openid.rb:98:in `call'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/rack/error_collector.rb:12:in `call'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/rack/agent_hooks.rb:22:in `call'
    vendor/bundle/ruby/2.0.0/gems/newrelic_rpm-3.6.5.130/lib/new_relic/rack/browser_monitoring.rb:16:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/etag.rb:23:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/head.rb:14:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/flash.rb:242:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/cookies.rb:341:in `call'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/query_cache.rb:64:in `call'
    vendor/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `_run__2299810304391740615__call__3275553076919854120__callbacks'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:405:in `__run_callback'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/callbacks.rb:81:in `run_callbacks'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:32:in `call_app'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `block in call'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/tagged_logging.rb:22:in `tagged'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/rack/logger.rb:16:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/request_id.rb:22:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
    vendor/bundle/ruby/2.0.0/gems/activesupport-3.2.13/lib/active_support/cache/strategy/local_cache.rb:72:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
    vendor/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/action_dispatch/middleware/static.rb:63:in `call'
    vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
    vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in `fetch'
    vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
    vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in `call!'
    vendor/bundle/ruby/2.0.0/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/engine.rb:479:in `call'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/application.rb:223:in `call'
    vendor/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/connection.rb:54:in `process'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/connection.rb:39:in `receive_data'
    vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
    vendor/bundle/ruby/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/backends/base.rb:63:in `start'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/server.rb:159:in `start'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/controllers/controller.rb:86:in `start'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/runner.rb:187:in `run_command'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/lib/thin/runner.rb:152:in `run!'
    vendor/bundle/ruby/2.0.0/gems/thin-1.5.1/bin/thin:6:in `<top (required)>'
    vendor/bundle/ruby/2.0.0/bin/thin:23:in `load'
    vendor/bundle/ruby/2.0.0/bin/thin:23:in `<main>'
```

**Comment by bcmedeiros** [comment]
What version of redmine are you using?

**Comment by tavlima** [comment]
As stated in the XML I posted, "2.3.2.devel".

**Comment by aVolpe** [comment]
Same message for version 2.3.3.devel

```
 <version api="2.8.2.stable" authenticated="true" authenticatedAs="XXXX">
      <plugin major="2" minor="8" tiny="2">2.8.2.stable</plugin>
      <redmine>2.3.3.devel</redmine>
      <rails>3.2.13</rails>
 </version>
```

**Comment by tchx84** [comment]
Just sent a pull request that solves this problem please check #21
