### ISSUE TITLE
not found xml, but installed and found manual

### ISSUE THREAD

**Issue by marku89** [danmunn/redmine_mylyn_connector#29]
Hey

I have some trouble with the libxml-ruby or our connector 

manual i get 
 # irb
irb(main):001:0> require 'rubygems'
=> true
irb(main):002:0> require 'xml'
=> true
irb(main):003:0> 

But when i use the rake test connector i get these 

redmine_bt/plugins/redmine_mylyn_connector # rake
/usr/bin/ruby -I"lib:lib:test" -I"/usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib" "/usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" 
/usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require': no such file to load -- xml (LoadError)
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
        from /srv/www/redmine_bt/plugins/redmine_mylyn_connector/lib/mylyn_connector/controller_test.rb:2
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in`require'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:359:in `require_or_load'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:502:in`load_missing_constant'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:192:in `const_missing'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:190:in`each'
        from /usr/lib64/ruby/gems/1.8/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:190:in `const_missing'
        from /srv/www/redmine_bt/plugins/redmine_mylyn_connector/test/functional/custom_fields_controller_test.rb:3
        from /srv/www/redmine_bt/plugins/redmine_mylyn_connector/test/functional/all_functional_test.rb:4:in`require'
        from /srv/www/redmine_bt/plugins/redmine_mylyn_connector/test/functional/all_functional_test.rb:4
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10:in `require'
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:10
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9:in`each'
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:9
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4:in `select'
        from /usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb:4
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test" -I"/usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib" "/usr/lib64/ruby/gems/1.8/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)

**Comment by marku89** [comment]
Build new stable ruby version , but still the same issue 
/usr/lib/ruby/gems/1.9.1/gems/activesupport-3.2.6/lib/active_support/dependencies.rb:251:in `require': cannot load such file -- xml (LoadError)
 # ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [s390x-linux]

**Comment by marku89** [comment]
Won't fix , latest report on this projekt is more than one year old !
