### ISSUE TITLE
404 Error when accessing tasks from Eclipse Luna - Redmine 3.0

### ISSUE THREAD

**Issue by sselvia** [danmunn/redmine_mylyn_connector#40]
After I had upgraded to redline 3.0 I started getting 404 errors from the mylyn eclipse plugin when I accessed any of my tasks.  This worked perfectly with redline 2.6.1.

Redmine Information:

Environment:
  Redmine version                3.0.0.stable.14044
  Ruby version                   2.0.0-p481 (2014-05-08) [universal.x86_64-darwin14]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.7.17
  Git                            2.0.1
  Filesystem  
Redmine plugins:
  redmine_mylyn_connector        2.8.2.stable

**Comment by Dawuid** [comment]
Maybe [this pull request](https://github.com/joaopedrotaveira/redmine_mylyn_connector/pull/1) could help you (for me works with Redmine 3.0.1 and Rails 4.2).

**Comment by stolp** [comment]
Thanks a lot David! I have a lot of people waiting for this.

**Comment by damiencuvillier** [comment]
I have same issue with a fresh git clone 

I'm not really comfortable with ruby but it seems version are quite the same than david. 
Any tips ?

Plugin appears in Redmine but it've got `Unexpected status code - 404` in eclipse plugin

My Configuration : 

```
Environment:
  Redmine version                3.1.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.3
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            2.1.4
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.3.11
  redmine_issues_tree            0.0.1
  redmine_mylyn_connector        2.8.2.stable

```

On Eclipse 

```
Eclipse Luna
Mylyn Connector: Redmine    0.4.0.201506191215  net.sf.redmine_mylyn.feature.feature.group
```

_rake_ command gives me

```
/usr/bin/ruby2.1 -I"lib:lib:test" -I"/var/lib/gems/2.1.0/gems/rake-10.4.2/lib" "/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/**/*_test.rb" 
Warning: you should require 'minitest/autorun' instead.
Warning: or add 'gem "minitest"' before 'require "minitest/autorun"'
From:
  /usr/lib/ruby/2.1.0/test/unit.rb:1:in `<top (required)>'
  /opt/redmine-3.1.0/plugins/redmine_mylyn_connector/test/functional/all_functional_test.rb:3:in `<top (required)>'
  /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
  /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:9:in `each'
  /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
  /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
  /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
MiniTest::Unit::TestCase is now Minitest::Test. From /usr/lib/ruby/2.1.0/test/unit/testcase.rb:8:in `<module:Unit>'
/usr/lib/ruby/2.1.0/test/unit.rb:676:in `<class:Runner>': undefined method `_run_suite' for class `Test::Unit::Runner' (NameError)
    from /usr/lib/ruby/2.1.0/test/unit.rb:261:in `<module:Unit>'
    from /usr/lib/ruby/2.1.0/test/unit.rb:15:in `<module:Test>'
    from /usr/lib/ruby/2.1.0/test/unit.rb:7:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /opt/redmine-3.1.0/plugins/redmine_mylyn_connector/test/functional/all_functional_test.rb:3:in `<top (required)>'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:10:in `block (2 levels) in <main>'
    from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:9:in `each'
    from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:9:in `block in <main>'
    from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `select'
    from /var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!

```

Try also _joaopedrotaveira_ pull request. Same result
