### ISSUE TITLE
undefined method matchers for method class

### ISSUE THREAD

**Issue by dominch** [danmunn/redmine_mylyn_connector#46]
hello 
I just updated plugin and that caused error 500, each rake task gives me error: 

```
undefined method `matchers' for Method:Class
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/dynamic_matchers.rb:62:in `<class:FindAllBy>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/dynamic_matchers.rb:61:in `<module:DynamicMatchers>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/dynamic_matchers.rb:4:in `<module:ActiveRecord>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders/dynamic_matchers.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `block in require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/dependencies.rb:251:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-deprecated_finders-1.0.4/lib/active_record/deprecated_finders.rb:7:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in `instance_eval'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:43:in `block in run_load_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:42:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-3.2.22/lib/active_support/lazy_load_hooks.rb:42:in `run_load_hooks'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/base.rb:720:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.1.5/gems/activerecord-3.2.22/lib/active_record/railtie.rb:33:in `block in <class:Railtie>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie.rb:194:in `instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie.rb:194:in `block in load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie.rb:194:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie.rb:194:in `load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/engine.rb:423:in `block in load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/application/railties.rb:8:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/application/railties.rb:8:in `all'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/engine.rb:423:in `load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/application.rb:145:in `load_tasks'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/data/redmine_test/Rakefile:7:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/rake_module.rb:25:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:637:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:165:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/lib/rake/application.rb:75:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/rake-10.1.1/bin/rake:33:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/bin/rake:23:in `load'
/usr/local/rvm/gems/ruby-2.1.5/bin/rake:23:in `<main>'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
rake aborted!
```

Redmine info: 

```
Environment:
  Redmine version                2.6.7.stable.14669
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  3.2.22
  Environment                    production
  Database adapter               Mysql2
```

**Comment by barbazul** [comment]
I'm having the same error during installation
