### ISSUE TITLE
404 Not Found - Mylyn, redmine and Eclipse

### ISSUE THREAD

**Issue by derMOE** [danmunn/redmine_mylyn_connector#48]
Hi,

I've installed redmine, eclipse and the mylyn_connector plugin in redmine and eclipse.

```
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_base_deface            0.0.1
  redmine_bootstrap_kit          0.2.3
  redmine_jenkins                1.0.1
  redmine_multiprojects_issue    0.2
  redmine_mylyn_connector        2.8.2.stable
```

I enabled REST Web Service inside redmine and filled out the properties for a Task Repository. If I click now on "New Query..." I'll get the following error message:

**Unexpected status code - 404 Not Found**

I can't see any error message in my log files...

When I click on "Validate Settings" everything seams fine: Test of connection was successful - Redmine 3.2.0 with Mylyn-Plugin 2.8.2

I want to use the API-Key variant.

Anyone can help me with the error message?!

Thx,
Markus

**Comment by aschreque** [comment]
Hi,

I have the same issue. I get the error log (without my API-KEY):

> App 4926 stderr: Processing by MylynConnector::IssuesController#show as XML
> App 4926 stderr:   Parameters: {"key"=>"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "id"=>"1"}
> App 4926 stderr:   Current user: aschreque (id=5)
> App 4926 stderr:   Rendered plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/_list_issue.xml.builder (37.3ms)
> App 4926 stderr:   Rendered plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/show.xml.builder (42.6ms)
> App 4926 stderr: Completed 500 Internal Server Error in 77ms (ActiveRecord: 18.0ms)
> App 4926 stderr: 
> App 4926 stderr: ActiveRecord::RecordNotFound (Couldn't find all Journals with 'id': (all, {:conditions=>["notes IS NOT NULL AND notes != ''"]}) [WHERE `journals`.`journalized_id` = ? AND `journals`.`journalized_type` = ?](found 0 results, but was looking for 2)):
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/helpers/mylyn_connector/issues_helper.rb:20:in `journals'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/_list_issue.xml.builder:48:in`block (2 levels) in _plugins_redmine_mylyn_connector_app_views_mylyn_connector_issues__list_issue_xml_builder___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/_list_issue.xml.builder:47:in `block in _plugins_redmine_mylyn_connector_app_views_mylyn_connector_issues__list_issue_xml_builder___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/_list_issue.xml.builder:1:in`_plugins_redmine_mylyn_connector_app_views_mylyn_connector_issues__list_issue_xml_builder___XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/views/mylyn_connector/issues/show.xml.builder:2:in `_plugins_redmine_mylyn_connector_app_views_mylyn_connector_issues_show_xml_builder__359XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/controllers/mylyn_connector/issues_controller.rb:24:in`block (2 levels) in show'
> App 4926 stderr:   plugins/redmine_mylyn_connector/app/controllers/mylyn_connector/issues_controller.rb:23:in `show'
> App 4926 stderr:   lib/redmine/sudo_mode.rb:63:in`sudo_mode'
> App 4926 stderr: 
> App 4926 stderr: '

**Comment by derMOE** [comment]
Which file is this?

**Comment by fhaefemeier** [comment]
This [pull request](https://github.com/joaopedrotaveira/redmine_mylyn_connector/pull/1) fixed it for me!
