### ISSUE TITLE
Problem using redmine_mylyn_connector, accessing from Eclipse Juno

### ISSUE THREAD

**Issue by gregn123** [danmunn/redmine_mylyn_connector#7]
I'm having problems using the "Mylyn Connector: Redmine" plugin for Eclipse (version 0.3.7.201203072118) in combination with the redmine_mylyn_connector; from Eclipse, I can't connect to the Redmine server when adding a Task Repository. 
I'm using Eclipse Juno (Eclipse Java EE IDE for Web Developers, Version: Juno Release, Build id: 20120614-1722).

I have Redmine 2.0.3 running on Windows Server 2008 R2.
I've installed the redmine_mylyn_connector (obtained from http://danmunn.github.com/redmine_mylyn_connector) with some minor Redmine configuration changes for using PostgreSQL instead of MySql.
The redmine_mylyn_connector was installed using "bundle install --without test sqlite mysql2 mysql rmagick development"

The Redmine Information page lists the following:

Environment:
  Redmine version                      2.0.3.stable
  Ruby version                            1.9.3 (i386-mingw32)
  Rails version                            3.2.6
  Environment                             production
  Database adapter                     PostgreSQL
Redmine plugins:
  redmine_mylyn_connector          2.8.2.stable

I can see an error in the Redmine production log, but not sure if it's related to the problem I'm having:

Started GET "/redmine/mylyn/version" for 127.0.0.1 at 2012-10-04 00:49:42 +0000

ActionController::RoutingError (uninitialized constant MylynConnector::InformationController):
  activesupport (3.2.6) lib/active_support/inflector/methods.rb:229:in `block in constantize'
  activesupport (3.2.6) lib/active_support/inflector/methods.rb:228:in`each'
  activesupport (3.2.6) lib/active_support/inflector/methods.rb:228:in `constantize'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:69:in`controller_reference'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:54:in `controller'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:32:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.6) lib/action_dispatch/routing/route_set.rb:600:in`call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.1) lib/rack/etag.rb:23:in `call'
  rack (1.4.1) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.1) lib/rack/session/abstract/id.rb:205:in`context'
  rack (1.4.1) lib/rack/session/abstract/id.rb:200:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/cookies.rb:338:in`call'
  activerecord (3.2.6) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:473:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in`_run__514267093__call__289363191__callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.6) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.6) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.6) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.6) lib/rails/rack/logger.rb:26:in`call_app'
  railties (3.2.6) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.6) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.1) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.6) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.1) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.6) lib/action_dispatch/middleware/static.rb:62:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.6) lib/rails/engine.rb:479:in `call'
  railties (3.2.6) lib/rails/application.rb:220:in`call'
  railties (3.2.6) lib/rails/railtie/configurable.rb:30:in `method_missing'
  rack (1.4.1) lib/rack/urlmap.rb:64:in`block in call'
  rack (1.4.1) lib/rack/urlmap.rb:49:in `each'
  rack (1.4.1) lib/rack/urlmap.rb:49:in`call'
  thin (1.4.1) lib/thin/connection.rb:80:in `block in pre_process'
  thin (1.4.1) lib/thin/connection.rb:78:in`catch'
  thin (1.4.1) lib/thin/connection.rb:78:in `pre_process'
  thin (1.4.1) lib/thin/connection.rb:53:in`process'
  thin (1.4.1) lib/thin/connection.rb:38:in `receive_data'
  eventmachine-1.0.0.rc.4-x86 (mingw32) lib/eventmachine.rb:187:in`run_machine'
  eventmachine-1.0.0.rc.4-x86 (mingw32) lib/eventmachine.rb:187:in `run'
  thin (1.4.1) lib/thin/backends/base.rb:63:in`start'
  thin (1.4.1) lib/thin/server.rb:159:in `start'
  thin (1.4.1) lib/thin/controllers/controller.rb:86:in`start'
  thin (1.4.1) lib/thin/runner.rb:185:in `run_command'
  thin (1.4.1) lib/thin/runner.rb:151:in`run!'
  thin (1.4.1) bin/thin:6:in `<top (required)>'
  C:/IT/ruby193/bin/thin:23:in`load'
  C:/IT/ruby193/bin/thin:23:in `<main>'

Any idea what could be the problem?

**Comment by ymlaine** [comment]
Same problem for me. Is it an incompatibilty with Eclipse Juno ?

**Comment by jkjwg** [comment]
I have the same problem,but I use eclipse 3.7 and I use bitnami to install redmine,also use the version 0.3.7 Mylyn Redmine Connector for eclipse , is there anything else should be done after  install the plugin (eg modify some config file etc ) ?

**Comment by kh4z** [comment]
Double check that your plugin directory name is redmine_mylyn_connector

**Comment by jkjwg** [comment]
Thanks a lot,changing the plugin directory name to redmine_mylyn_connector help me solve the problem,but another problem comes next. when I adding a Task Repository in eclipse and try validate settings, it is failed with msg "invalid credentials" and the error msg in production.log shows the user is anonymous,but I am sure that I set the user_id, the information I set like this:
Server:http://localhost:88/redmine
Label:redmine
User ID:wg
Password:111111

Of course, I can login into redmine with userId and password above.  Is there any suggestion about this error?

**Comment by vskubriev** [comment]
> Double check that your plugin directory name is redmine_mylyn_connector
> This helps me too.
